name: e_commerce_app
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  # --------- Icon ---------- #
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  lottie: ^3.3.1

  # ---------- State Management ----------- #
  get: ^4.7.2
  get_storage: ^2.1.1

  # ---------- Utility Package ----------- #
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  flutter_native_splash: ^2.4.6

  # ---------- Firebase ----------- #
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11

  # ---------- Auth ----------- #
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.3.0


  # ----------- Other ------------ #
  flutter_secure_storage: ^9.2.4
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.5.2
  google_fonts: ^6.3.0
  google_maps_flutter: ^2.14.0
  image_picker: ^1.1.2

  # ----------- Network ------------ #
  connectivity_plus: ^6.1.4

  # Product Specific
  readmore: ^3.0.0
  flutter_staggered_animations: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # ===================== //   Init assets   // ======================== #

  assets:
    # --------------  //    Image    //  ------------------- #
    - assets/images/on_boarding_images/
    - assets/images/productions/
    - assets/images/others/
    - assets/images/banners/
    - assets/images/user/

    # --------------  //    Logo    //  -------------------- #
    - assets/logos/
    - assets/logos/splash/
    # --------------  //    Icon    //  -------------------- #
    - assets/icons/payment_method/
    - assets/icons/category/

    # --------------  // Animation //  ----------------#
    - assets/animations/


  # ================= //    How to Customise Fonts  // ==================== #

  #  fonts:
  #     - family: Schyler
  #       fonts:
  #         - asset: fonts/Schyler-Regular.ttf
  #         - asset: fonts/Schyler-Italic.ttf
  #           style: italic
